# -*- coding: utf-8 -*-
# Deployment settings for OpenGL_ES_Training.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['C:/Program Files/Marmalade/6.0/s3e/makefile_builder/mkb.py', '--open-with-wmlaunchpad', 'G:/1WorkSpace/MyGit/opengl_es_training/OpenGL_ES_Training/OpenGL_ES_Training.mkb', '--deploy-only']
mkb = 'G:/1WorkSpace/MyGit/opengl_es_training/OpenGL_ES_Training/OpenGL_ES_Training.mkb'
mkf = ['c:\\program files\\marmalade\\6.0\\modules\\iwgl\\iwgl.mkf', 'c:\\program files\\marmalade\\6.0\\modules\\iwutil\\iwutil.mkf', u'f:\\users\\pclass\\appdata\\roaming\\marmalade\\packages\\6.0.5\\libjpeg_6b\\libjpeg.mkf', u'f:\\users\\pclass\\appdata\\roaming\\marmalade\\packages\\6.0.5\\libpng_1.2.34\\libpng.mkf', u'f:\\users\\pclass\\appdata\\roaming\\marmalade\\packages\\6.0.5\\zlib_1.2.4\\zlib.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('G:/1WorkSpace/MyGit/opengl_es_training/OpenGL_ES_Training\data', '.', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'OpenGL_ES_Training'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'OpenGL_ES_Training'
    long_caption = 'OpenGL_ES_Training'
    version = [0, 0, 1]
    config = ['G:/1WorkSpace/MyGit/opengl_es_training/OpenGL_ES_Training/data/app.icf']
    data_dir = 'G:/1WorkSpace/MyGit/opengl_es_training/OpenGL_ES_Training/data'
    iphone_link_lib = []
    linux_ext_lib = []
    iphone_link_libdir = []
    iphone_link_opts = []
    osx_ext_dll = []
    android_external_jars = []
    android_external_res = []
    android_supports_gl_texture = []
    android_extra_manifest = []
    iphone_link_libdirs = []
    android_extra_application_manifest = []
    win32_ext_dll = []
    android_so = []
    iphone_link_libs = []
    target = {
         'arm' : {
                   'debug'   : r'G:/1WorkSpace/MyGit/opengl_es_training/OpenGL_ES_Training/build_opengl_es_training_vc10/Debug_OpenGL_ES_Training_VC10_arm/OpenGL_ES_Training.s3e',
                   'release' : r'G:/1WorkSpace/MyGit/opengl_es_training/OpenGL_ES_Training/build_opengl_es_training_vc10/Release_OpenGL_ES_Training_VC10_arm/OpenGL_ES_Training.s3e',
                 },
         'mips_gcc' : {
                   'debug'   : r'G:/1WorkSpace/MyGit/opengl_es_training/OpenGL_ES_Training/build_opengl_es_training_vc10/Debug_OpenGL_ES_Training_VC10_gcc_mips/OpenGL_ES_Training.so',
                   'release' : r'G:/1WorkSpace/MyGit/opengl_es_training/OpenGL_ES_Training/build_opengl_es_training_vc10/Release_OpenGL_ES_Training_VC10_gcc_mips/OpenGL_ES_Training.so',
                 },
         'x86' : {
                   'debug'   : r'G:/1WorkSpace/MyGit/opengl_es_training/OpenGL_ES_Training/build_opengl_es_training_vc10/Debug_OpenGL_ES_Training_VC10_x86/OpenGL_ES_Training.s86',
                   'release' : r'G:/1WorkSpace/MyGit/opengl_es_training/OpenGL_ES_Training/build_opengl_es_training_vc10/Release_OpenGL_ES_Training_VC10_x86/OpenGL_ES_Training.s86',
                 },
         'arm_gcc' : {
                   'debug'   : r'G:/1WorkSpace/MyGit/opengl_es_training/OpenGL_ES_Training/build_opengl_es_training_vc10/Debug_OpenGL_ES_Training_VC10_gcc_arm/OpenGL_ES_Training.s3e',
                   'release' : r'G:/1WorkSpace/MyGit/opengl_es_training/OpenGL_ES_Training/build_opengl_es_training_vc10/Release_OpenGL_ES_Training_VC10_gcc_arm/OpenGL_ES_Training.s3e',
                 },
        }
    assets = assets['Default']

default = DefaultConfig()
